remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
exclude: []
title: Omar Malas
description: "About Omar Malas"
baseurl: "https://omarmalas.github.io" # The base URL of your site (e.g., "/blog" for a subfolder)
url: "https://omarmalas.github.io" # Replace with your GitHub username

